spring:
  mail:
    host: mail.ru
    port: 465
    username: eva@hubertm.ru
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: true
